{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from tools.imdb_multproc import ret_imdb_data_parallel\n",
    "import pandas as pd\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "imdb_responses=pd.read_pickle(\"all_imdb_responses.pkl\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "imdb_ids=[\"\" if type(row)==str else row.movieID for row in imdb_responses]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "id_df=pd.DataFrame({\"IMDB ID\":imdb_ids})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "id_df_10000=id_df.iloc[:10000]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-12-15 17:08:01,260 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:08:20,635 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:08:46,431 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:08:48,477 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:09:24,707 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:09:49,215 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:09:58,828 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:10:02,889 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:10:14,116 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:10:16,452 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:10:20,704 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:10:37,283 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:10:37,945 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:10:48,586 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:10:51,637 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:10:57,620 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:10:58,347 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:11:14,209 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:11:19,510 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:11:22,703 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:11:33,337 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:11:47,989 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:11:48,530 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:12:22,758 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:12:24,094 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:12:46,743 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:12:52,748 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:12:58,830 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:13:00,451 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:13:04,014 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:13:09,315 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:13:09,316 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:13:38,514 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:13:42,868 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:13:43,283 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:14:31,773 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:15:25,692 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:15:34,719 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:15:37,537 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:15:43,970 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:15:44,833 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt0399414/plotsummary', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 504: 'Gateway Time-out'>},); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 233, in retrieve_unicode\n",
      "    response = uopener.open(url)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 523, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 632, in http_response\n",
      "    response = self.parent.error(\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 561, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 494, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 641, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 504: Gateway Time-out\n",
      "2023-12-15 17:15:44,836 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/__init__.py:850: caught an exception retrieving or parsing \"plot\" info set for mopID \"0399414\" (accessSystem: http)\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 233, in retrieve_unicode\n",
      "    response = uopener.open(url)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 523, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 632, in http_response\n",
      "    response = self.parent.error(\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 561, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 494, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 641, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 504: Gateway Time-out\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/__init__.py\", line 848, in update\n",
      "    ret = method(mopID)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 498, in get_movie_plot\n",
      "    cont = self._retrieve(self.urls['movie_main'] % movieID + 'plotsummary')\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 392, in _retrieve\n",
      "    ret = self.urlOpener.retrieve_unicode(url, size=size)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 261, in retrieve_unicode\n",
      "    raise IMDbDataAccessError(\n",
      "imdb._exceptions.IMDbDataAccessError: {'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt0399414/plotsummary', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 504: 'Gateway Time-out'>}\n",
      "2023-12-15 17:15:46,859 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:15:54,907 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:15:57,354 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:16:07,732 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:16:44,697 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:16:50,946 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:17:07,878 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:17:22,099 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:17:22,637 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:17:24,289 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:17:28,496 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:17:28,496 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:18:17,959 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:18:58,078 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:19:39,089 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:20:12,038 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:20:14,462 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:20:14,736 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:20:52,559 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:20:58,023 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:21:17,545 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:21:26,432 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:22:13,900 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:22:14,964 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:22:19,602 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:22:43,717 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:22:51,430 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:22:56,381 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:24:18,218 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:24:39,746 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:24:41,992 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:25:01,232 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:25:18,353 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:25:19,352 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:25:29,213 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:25:35,389 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:25:54,018 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:25:57,163 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:26:33,819 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:26:46,059 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:27:06,338 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:27:26,421 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:27:43,775 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:27:46,694 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:27:50,449 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:29:02,183 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:29:03,174 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt0023455/plotsummary', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 502: 'Bad Gateway'>},); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 233, in retrieve_unicode\n",
      "    response = uopener.open(url)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 523, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 632, in http_response\n",
      "    response = self.parent.error(\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 555, in error\n",
      "    result = self._call_chain(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 494, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 159, in http_error_308\n",
      "    return super(IMDbHTTPRedirectHandler, self).http_error_302(req, fp, code, msg, headers)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 747, in http_error_302\n",
      "    return self.parent.open(new, timeout=req.timeout)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 523, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 632, in http_response\n",
      "    response = self.parent.error(\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 561, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 494, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 641, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 502: Bad Gateway\n",
      "2023-12-15 17:29:03,180 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/__init__.py:850: caught an exception retrieving or parsing \"plot\" info set for mopID \"0023455\" (accessSystem: http)\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 233, in retrieve_unicode\n",
      "    response = uopener.open(url)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 523, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 632, in http_response\n",
      "    response = self.parent.error(\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 555, in error\n",
      "    result = self._call_chain(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 494, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 159, in http_error_308\n",
      "    return super(IMDbHTTPRedirectHandler, self).http_error_302(req, fp, code, msg, headers)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 747, in http_error_302\n",
      "    return self.parent.open(new, timeout=req.timeout)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 523, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 632, in http_response\n",
      "    response = self.parent.error(\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 561, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 494, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 641, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 502: Bad Gateway\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/__init__.py\", line 848, in update\n",
      "    ret = method(mopID)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 498, in get_movie_plot\n",
      "    cont = self._retrieve(self.urls['movie_main'] % movieID + 'plotsummary')\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 392, in _retrieve\n",
      "    ret = self.urlOpener.retrieve_unicode(url, size=size)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 261, in retrieve_unicode\n",
      "    raise IMDbDataAccessError(\n",
      "imdb._exceptions.IMDbDataAccessError: {'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt0023455/plotsummary', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 502: 'Bad Gateway'>}\n",
      "2023-12-15 17:29:10,449 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:29:28,601 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:29:41,878 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:29:43,063 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:29:49,056 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:29:55,492 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:30:16,863 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:30:21,675 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:30:39,181 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:31:12,850 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:31:16,210 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:31:23,108 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:31:28,264 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:32:24,273 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:32:28,989 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:32:40,381 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:33:11,301 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:33:15,190 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:33:27,045 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:33:29,668 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:33:36,265 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:33:46,163 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:34:38,403 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:34:47,637 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:34:48,436 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:34:57,003 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt0004527/plotsummary', 'proxy': '', 'exception type': 'IOError', 'original exception': timeout('The read operation timed out')},); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 233, in retrieve_unicode\n",
      "    response = uopener.open(url)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 523, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 632, in http_response\n",
      "    response = self.parent.error(\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 555, in error\n",
      "    result = self._call_chain(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 494, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 159, in http_error_308\n",
      "    return super(IMDbHTTPRedirectHandler, self).http_error_302(req, fp, code, msg, headers)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 747, in http_error_302\n",
      "    return self.parent.open(new, timeout=req.timeout)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 517, in open\n",
      "    response = self._open(req, data)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 534, in _open\n",
      "    result = self._call_chain(self.handle_open, protocol, protocol +\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 494, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 1389, in https_open\n",
      "    return self.do_open(http.client.HTTPSConnection, req,\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 1350, in do_open\n",
      "    r = h.getresponse()\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/http/client.py\", line 1377, in getresponse\n",
      "    response.begin()\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/http/client.py\", line 320, in begin\n",
      "    version, status, reason = self._read_status()\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/http/client.py\", line 281, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/socket.py\", line 704, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/ssl.py\", line 1242, in recv_into\n",
      "    return self.read(nbytes, buffer)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/ssl.py\", line 1100, in read\n",
      "    return self._sslobj.read(len, buffer)\n",
      "socket.timeout: The read operation timed out\n",
      "2023-12-15 17:34:57,010 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/__init__.py:850: caught an exception retrieving or parsing \"plot\" info set for mopID \"0004527\" (accessSystem: http)\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 233, in retrieve_unicode\n",
      "    response = uopener.open(url)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 523, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 632, in http_response\n",
      "    response = self.parent.error(\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 555, in error\n",
      "    result = self._call_chain(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 494, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 159, in http_error_308\n",
      "    return super(IMDbHTTPRedirectHandler, self).http_error_302(req, fp, code, msg, headers)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 747, in http_error_302\n",
      "    return self.parent.open(new, timeout=req.timeout)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 517, in open\n",
      "    response = self._open(req, data)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 534, in _open\n",
      "    result = self._call_chain(self.handle_open, protocol, protocol +\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 494, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 1389, in https_open\n",
      "    return self.do_open(http.client.HTTPSConnection, req,\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 1350, in do_open\n",
      "    r = h.getresponse()\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/http/client.py\", line 1377, in getresponse\n",
      "    response.begin()\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/http/client.py\", line 320, in begin\n",
      "    version, status, reason = self._read_status()\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/http/client.py\", line 281, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/socket.py\", line 704, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/ssl.py\", line 1242, in recv_into\n",
      "    return self.read(nbytes, buffer)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/ssl.py\", line 1100, in read\n",
      "    return self._sslobj.read(len, buffer)\n",
      "socket.timeout: The read operation timed out\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/__init__.py\", line 848, in update\n",
      "    ret = method(mopID)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 498, in get_movie_plot\n",
      "    cont = self._retrieve(self.urls['movie_main'] % movieID + 'plotsummary')\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 392, in _retrieve\n",
      "    ret = self.urlOpener.retrieve_unicode(url, size=size)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 261, in retrieve_unicode\n",
      "    raise IMDbDataAccessError(\n",
      "imdb._exceptions.IMDbDataAccessError: {'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt0004527/plotsummary', 'proxy': '', 'exception type': 'IOError', 'original exception': timeout('The read operation timed out')}\n",
      "2023-12-15 17:35:07,413 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:36:20,787 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:36:21,080 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:36:49,629 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:36:52,036 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:37:04,771 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:37:15,429 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:38:04,176 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:38:06,169 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:38:50,164 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:39:00,213 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:39:11,638 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:39:25,207 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:39:36,684 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:39:49,612 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:40:02,402 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:40:26,824 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:40:39,468 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:40:46,099 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:41:10,508 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:41:43,716 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:41:52,727 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:41:53,305 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:41:53,306 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:42:01,994 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:42:06,890 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:42:13,989 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:42:19,947 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:42:49,632 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt0266298/plotsummary', 'proxy': '', 'exception type': 'IOError', 'original exception': timeout('The read operation timed out')},); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 233, in retrieve_unicode\n",
      "    response = uopener.open(url)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 523, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 632, in http_response\n",
      "    response = self.parent.error(\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 555, in error\n",
      "    result = self._call_chain(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 494, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 159, in http_error_308\n",
      "    return super(IMDbHTTPRedirectHandler, self).http_error_302(req, fp, code, msg, headers)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 747, in http_error_302\n",
      "    return self.parent.open(new, timeout=req.timeout)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 517, in open\n",
      "    response = self._open(req, data)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 534, in _open\n",
      "    result = self._call_chain(self.handle_open, protocol, protocol +\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 494, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 1389, in https_open\n",
      "    return self.do_open(http.client.HTTPSConnection, req,\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 1350, in do_open\n",
      "    r = h.getresponse()\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/http/client.py\", line 1377, in getresponse\n",
      "    response.begin()\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/http/client.py\", line 320, in begin\n",
      "    version, status, reason = self._read_status()\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/http/client.py\", line 281, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/socket.py\", line 704, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/ssl.py\", line 1242, in recv_into\n",
      "    return self.read(nbytes, buffer)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/ssl.py\", line 1100, in read\n",
      "    return self._sslobj.read(len, buffer)\n",
      "socket.timeout: The read operation timed out\n",
      "2023-12-15 17:42:49,646 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/__init__.py:850: caught an exception retrieving or parsing \"plot\" info set for mopID \"0266298\" (accessSystem: http)\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 233, in retrieve_unicode\n",
      "    response = uopener.open(url)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 523, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 632, in http_response\n",
      "    response = self.parent.error(\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 555, in error\n",
      "    result = self._call_chain(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 494, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 159, in http_error_308\n",
      "    return super(IMDbHTTPRedirectHandler, self).http_error_302(req, fp, code, msg, headers)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 747, in http_error_302\n",
      "    return self.parent.open(new, timeout=req.timeout)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 517, in open\n",
      "    response = self._open(req, data)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 534, in _open\n",
      "    result = self._call_chain(self.handle_open, protocol, protocol +\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 494, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 1389, in https_open\n",
      "    return self.do_open(http.client.HTTPSConnection, req,\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 1350, in do_open\n",
      "    r = h.getresponse()\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/http/client.py\", line 1377, in getresponse\n",
      "    response.begin()\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/http/client.py\", line 320, in begin\n",
      "    version, status, reason = self._read_status()\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/http/client.py\", line 281, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/socket.py\", line 704, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/ssl.py\", line 1242, in recv_into\n",
      "    return self.read(nbytes, buffer)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/ssl.py\", line 1100, in read\n",
      "    return self._sslobj.read(len, buffer)\n",
      "socket.timeout: The read operation timed out\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/__init__.py\", line 848, in update\n",
      "    ret = method(mopID)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 498, in get_movie_plot\n",
      "    cont = self._retrieve(self.urls['movie_main'] % movieID + 'plotsummary')\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 392, in _retrieve\n",
      "    ret = self.urlOpener.retrieve_unicode(url, size=size)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 261, in retrieve_unicode\n",
      "    raise IMDbDataAccessError(\n",
      "imdb._exceptions.IMDbDataAccessError: {'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt0266298/plotsummary', 'proxy': '', 'exception type': 'IOError', 'original exception': timeout('The read operation timed out')}\n",
      "2023-12-15 17:42:55,740 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:43:23,903 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:43:27,611 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:43:38,060 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt1700808/plotsummary', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 504: 'Gateway Time-out'>},); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 233, in retrieve_unicode\n",
      "    response = uopener.open(url)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 523, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 632, in http_response\n",
      "    response = self.parent.error(\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 561, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 494, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 641, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 504: Gateway Time-out\n",
      "2023-12-15 17:43:38,065 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/__init__.py:850: caught an exception retrieving or parsing \"plot\" info set for mopID \"1700808\" (accessSystem: http)\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 233, in retrieve_unicode\n",
      "    response = uopener.open(url)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 523, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 632, in http_response\n",
      "    response = self.parent.error(\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 561, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 494, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 641, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 504: Gateway Time-out\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/__init__.py\", line 848, in update\n",
      "    ret = method(mopID)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 498, in get_movie_plot\n",
      "    cont = self._retrieve(self.urls['movie_main'] % movieID + 'plotsummary')\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 392, in _retrieve\n",
      "    ret = self.urlOpener.retrieve_unicode(url, size=size)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 261, in retrieve_unicode\n",
      "    raise IMDbDataAccessError(\n",
      "imdb._exceptions.IMDbDataAccessError: {'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt1700808/plotsummary', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 504: 'Gateway Time-out'>}\n",
      "2023-12-15 17:43:44,110 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:43:51,125 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:43:59,437 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:44:09,454 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:44:09,960 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:44:14,591 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:44:53,707 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:45:10,670 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:45:18,595 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:45:21,537 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:45:34,666 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:45:38,920 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:45:49,271 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:46:16,422 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:46:48,594 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:46:57,745 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:47:04,176 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:47:17,213 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:47:17,463 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:47:33,318 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:47:36,464 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:47:43,744 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:47:51,286 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m/var/folders/l1/8zt_lx6x0814k8sr48r34sk00000gn/T/ipykernel_34454/4026157360.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mret_imdb_data_parallel\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m10\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0mid_df_10000\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"id\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/Documents/GitHub/ada-2023-project-preprocessedpeoples/tools/imdb_multproc.py\u001b[0m in \u001b[0;36mret_imdb_data_parallel\u001b[0;34m(N, dataset, retrieve_with)\u001b[0m\n\u001b[1;32m     46\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     47\u001b[0m     \u001b[0;32mfor\u001b[0m \u001b[0mp\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mprocesses\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 48\u001b[0;31m         \u001b[0mp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjoin\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     49\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     50\u001b[0m     \u001b[0mresults\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/multiprocessing/process.py\u001b[0m in \u001b[0;36mjoin\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    147\u001b[0m         \u001b[0;32massert\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_parent_pid\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0mos\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgetpid\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'can only join a child process'\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    148\u001b[0m         \u001b[0;32massert\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_popen\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'can only join a started process'\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 149\u001b[0;31m         \u001b[0mres\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_popen\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    150\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mres\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    151\u001b[0m             \u001b[0m_children\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdiscard\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/multiprocessing/popen_fork.py\u001b[0m in \u001b[0;36mwait\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m     41\u001b[0m                     \u001b[0;32mreturn\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     42\u001b[0m             \u001b[0;31m# This shouldn't block if wait() returned successfully.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 43\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpoll\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mos\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mWNOHANG\u001b[0m \u001b[0;32mif\u001b[0m \u001b[0mtimeout\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;36m0.0\u001b[0m \u001b[0;32melse\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     44\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mreturncode\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     45\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/multiprocessing/popen_fork.py\u001b[0m in \u001b[0;36mpoll\u001b[0;34m(self, flag)\u001b[0m\n\u001b[1;32m     25\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mreturncode\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     26\u001b[0m             \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 27\u001b[0;31m                 \u001b[0mpid\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msts\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mos\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwaitpid\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpid\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mflag\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     28\u001b[0m             \u001b[0;32mexcept\u001b[0m \u001b[0mOSError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     29\u001b[0m                 \u001b[0;31m# Child process not yet created. See #1731717\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-12-15 17:48:14,981 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:48:16,706 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:48:26,994 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:48:45,452 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:48:55,781 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:49:11,566 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:49:22,121 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:49:40,710 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:50:06,379 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:50:20,279 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:50:48,297 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt0040292/plotsummary', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 504: 'Gateway Time-out'>},); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 233, in retrieve_unicode\n",
      "    response = uopener.open(url)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 523, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 632, in http_response\n",
      "    response = self.parent.error(\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 561, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 494, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 641, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 504: Gateway Time-out\n",
      "2023-12-15 17:50:48,299 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/__init__.py:850: caught an exception retrieving or parsing \"plot\" info set for mopID \"0040292\" (accessSystem: http)\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 233, in retrieve_unicode\n",
      "    response = uopener.open(url)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 523, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 632, in http_response\n",
      "    response = self.parent.error(\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 561, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 494, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/urllib/request.py\", line 641, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 504: Gateway Time-out\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/__init__.py\", line 848, in update\n",
      "    ret = method(mopID)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 498, in get_movie_plot\n",
      "    cont = self._retrieve(self.urls['movie_main'] % movieID + 'plotsummary')\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 392, in _retrieve\n",
      "    ret = self.urlOpener.retrieve_unicode(url, size=size)\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 261, in retrieve_unicode\n",
      "    raise IMDbDataAccessError(\n",
      "imdb._exceptions.IMDbDataAccessError: {'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt0040292/plotsummary', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 504: 'Gateway Time-out'>}\n",
      "2023-12-15 17:50:57,006 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:51:15,995 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:51:28,627 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:51:29,678 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:51:40,406 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:51:49,518 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:51:57,438 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:52:09,458 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:52:33,456 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:52:46,297 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:53:02,133 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:53:04,424 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:53:05,257 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:53:20,645 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:53:26,384 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:53:38,971 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:53:48,917 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:53:49,243 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:53:49,243 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:54:21,047 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:54:46,838 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:54:48,319 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:54:50,736 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:54:53,297 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:54:57,366 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:55:07,476 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:55:08,611 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:55:12,208 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:55:13,571 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:55:24,496 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:55:41,659 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:55:58,349 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:56:26,093 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:56:26,351 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:56:26,976 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:56:57,645 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:57:53,289 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:58:13,901 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:58:15,466 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:58:29,305 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:58:42,428 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:59:00,999 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n",
      "2023-12-15 17:59:52,741 CRITICAL [imdbpy] /Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbParserError exception raised; args: ('invalid movieID \"\": invalid literal for int() with base 10: \\'\\'',); kwds: {}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/berkeargin/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py\", line 313, in _normalize_movieID\n",
      "    return '%07d' % int(movieID)\n",
      "ValueError: invalid literal for int() with base 10: ''\n"
     ]
    }
   ],
   "source": [
    "ret_imdb_data_parallel(10,id_df_10000, \"id\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
